---

- file: path="/etc/kubernetes/admission-controls" state=directory
  name: assure admission-controls dir exists

- include: gen_token.yml
  name: starting generate tokens

# - set_fact: 
#     tokens: "{{ hostvars[groups['masters'][0]].tokens }}"
#   when: "{{ 'nodes' in group_names }}"

- file: path={{ kube_cert_dir }} state=directory
  name: "mkdir {{ kube_cert_dir }} on everywhere"

- name: "generate certs on {{ groups['masters'][0] }}"
  include: gen_certs.yml
  when: inventory_hostname == groups['masters'][0]

- name: read ca.crt
  slurp: src=/tmp/k8s/easy-rsa-master/easyrsa3/pki/ca.crt
  register: ca_crt
  delegate_to: "{{ groups['masters'][0] }}"

- copy: >
    content={{ ca_crt.content|b64decode }}
    dest={{ kube_cert_dir }}/ca.crt
  name: "copy ca.crt to {{ kube_cert_dir }}"

- lineinfile: dest="{{known_basic_auth}}" regexp=admin,admin line="admin,admin,admin" create=yes
  delegate_to: "{{ groups['masters'][0] }}"

# - include: gen_node_crt.yml
#   when: inventory_hostname == groups['masters'][0]