---
- hosts: etcd
  become: yes
  roles:
    - etcd
  tags:
    - etcd

- hosts:
    - nodes
    - masters
  become: yes
  roles:
    - docker
    - flannel
  tags:
    - nodes

- hosts: 
    - masters
  become: yes
  roles:
    - master
  tags:
    - k8s
    - masters

- hosts:
    - nodes
  become: yes
  roles:
    - node
  tags:
    - k8s
    - join

- hosts: masters
  become: yes
  roles:
    - "kube-addons"
  tags:
    - masters
    - k8s
    - addons

- hosts: glusters
  become: yes
  roles:
    - gluster
  tags:
    - glusters

#set_fact:
#  ansible_default_ipv4: "{{ 'ansible_' + private_network_iface['ipv4'] }}"
# vim:ft=ansible:
