---
- hosts: etcd
  become: yes
  roles:
    - etcd
  tags:
    - etcd
    - masters

- hosts: nodes
  become: yes
  roles:
    - docker
    - flannel
  tags:
    - nodes

- hosts: glusters
  become: yes
  roles:
    - gluster
  tags:
    - glusters

- hosts: masters
  become: yes
  roles:
    - tls
  tags:
    - masters

#set_fact:
#  ansible_default_ipv4: "{{ 'ansible_' + private_network_iface['ipv4'] }}"
# vim:ft=ansible:
