---
- hosts: etcd
  become: yes
  roles:
    - etcd
  tags:
    - etcd

- hosts: nodes
  become: yes
  roles:
    - docker
    - flannel
  tags:
    - nodes

- hosts: 
    - masters
  become: yes
  roles:
    - master
    - "kube-addons"
  tags:
    - masters

- hosts:
    - nodes
  become: yes
  roles:
    - node
  tags:
    - join

- hosts: glusters
  become: yes
  roles:
    - gluster
  tags:
    - glusters

#set_fact:
#  ansible_default_ipv4: "{{ 'ansible_' + private_network_iface['ipv4'] }}"
# vim:ft=ansible:
