---
- hosts: etcd
  become: yes
  roles:
    - etcd
  tags:
    - etcd
    - master

- hosts: nodes
  become: yes
  roles:
    - docker
    - flannel
  tags:
    - nodes

- hosts: glusters
  become: yes
  roles:
    - gluster
  tags:
    - glusters

# vim:ft=ansible:
