---
- set_fact: 
    etcd_version: "v2.0.12"

- local_action:
    file path=downloads state=directory
  become: no

- name: "download etcd github release tag {{ etcd_version }}"
  local_action:
    get_url
      url="https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
      dest="downloads/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
  become: no

- local_action:
    shell pwd
  register: current_pwd
  changed_when: false
  become: no

- local_action:
    unarchive
      src="{{ current_pwd.stdout }}/downloads/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
      dest="{{ current_pwd.stdout }}/downloads"
      copy=yes
  become: no
#- name: create download dir
#  file: "path={{ etcd_download_dir }} state=directory"

# - unarchive:
#   #src: "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
#     src: "../files/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
#     dest: /usr/local
#     copy: yes

- name: "copy binaries to /usr/local/bin"
  copy:
    src: downloads/etcd-{{ etcd_version }}-linux-amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: "0774"
  with_items:
    - etcd
    - etcdctl

#- copy: src=etcd.upstart dest=/etc/init/etcd.conf state=absent

- file: path="/etc/etcd" state=directory

- file: "path={{ etcd_data_dir }} state=directory"

- template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  notify:
    - restart etcd

- copy: src=etcd.service dest=/etc/systemd/system
  notify:
    - reload systemd
    - restart etcd

# vim:ft=ansible:
