---
- include: github-release.yml
  become: no
  run_onece: true

- set_fact:
    kube_apiserver: "{% for master in groups['masters'] %}https://{{ hostvars[master]['ansible_' + private_network_iface].ipv4.address }}:{{ kube_api_secure_port }}{% if not loop.last %},{% endif %}{% endfor %}"

- shell: |
    uname -a | grep  -i darwin || true
  register: darwin

- local_action:
    file
      src="{{server_bin.stat.path}}/kubectl"
      dest=/usr/local/bin/kubectl
      mode=u+x
  become: no
  when: darwin.stdout == ""

- local_action:
    shell
      if ! [ -f /usr/local/bin/kubectl ]; then
        curl -o /usr/local/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/{{kube_relase_ver}}/bin/darwin/amd64/kubectl";
        chmod +x /usr/local/bin/kubectl;
      fi
  when: darwin.stdout != ""
