---
- include: github-release.yml
  become: no
  run_onece: true

- set_fact:
    kube_apiserver: "{% for master in groups['masters'] %}https://{{ hostvars[master]['ansible_' + private_network_iface].ipv4.address }}:{{ kube_api_secure_port }}{% if not loop.last %},{% endif %}{% endfor %}"

- local_action:
    file
      src="{{server_bin.stat.path}}/kubectl"
      dest=/usr/local/bin/kubectl
      mode=u+x
  become: no
