---
- set_fact:
    flannel_version: 0.5.5

- local_action:
    file path=downloads state=directory
  become: no

- name: "download flannel github release tag {{ flannel_version }}"
  local_action:
    get_url
      url="https://github.com/coreos/flannel/releases/download/v{{ flannel_version }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
      dest="downloads/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
  become: no

- local_action:
    shell pwd
  register: current_pwd
  changed_when: false
  become: no

- local_action:
    unarchive
      src="{{ current_pwd.stdout }}/downloads/flannel-{{ flannel_version }}-linux-amd64.tar.gz"
      dest="{{ current_pwd.stdout }}/downloads"
      copy=yes
      creates="{{ current_pwd.stdout }}/downloads/flannel-{{ flannel_version }}/flanneld"
  become: no
  name: unarchive flannel

- copy:
    src: downloads/flannel-{{ flannel_version }}/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: "0774"
  with_items:
    - "flanneld"
    - "mk-docker-opts.sh"

- file: "path={{ item }} state=directory"
  with_items:
    - "/run"
    - "/etc/flanneld"

- template: src=flanneld.conf.j2 dest=/etc/flanneld/flanneld.conf
  notify:
    - restart flanneld

- copy: src=flanneld.service dest=/etc/systemd/system
  notify:
    - reload systemd
    - restart flanneld