---

etcd_source_type: github-release

etcd_url_scheme: http
etcd_peer_url_scheme: http
etcd_peer_port: 2380
etcd_client_port: 2379

etcd_peers_group: etcd
etcd_conf_dir: /etc/etcd
etcd_data_dir: /var/lib/etcd


etcd_initial_advertise_peer_urls: "{{ etcd_peer_url_scheme }}://{{ ansible_fqdn }}:{{ etcd_peer_port }}"
etcd_listen_peer_urls: "{{ etcd_peer_url_scheme }}://0.0.0.0:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "{{ etcd_url_scheme }}://{{ ansible_fqdn }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "{{ etcd_url_scheme }}://0.0.0.0:{{ etcd_client_port }}"

etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-k8-cluster
