---
- set_fact: 
    docker_version: "1.7.1-0~jessie"

- name: check apt last update
  stat: path=/var/cache/apt
  register: apt_cache_stat
- name: update apt if needed
  apt: update_cache=yes
  when: ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12

- apt: "name={{ item }} purge=yes state=absent"
  with_items:
    - "lxc-docker"
    - "docker.io" 

- apt: "name={{ item }} state=present"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"

- apt_key: 
    keyserver: hkp://p80.pool.sks-keyservers.net:80 
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- apt_repository: 
    repo: "deb https://apt.dockerproject.org/repo debian-jessie main"
    #filename: "docker.list"

- command: apt-cache policy docker-engine
  register: docker_packages

- file: path="/etc/systemd/system/docker.service.d" state=directory

- name: write docker drop-in
  copy:
    src: 10-override.conf
    dest: /etc/systemd/system/docker.service.d/10-extra-opts.conf
  notify:
    - reload systemd
    # - restart docker

- template: src=docker-opts.j2 dest=/etc/default/docker
  notify:
    - restart flanneld
#- debug: var=docker_packages

- name: "install docker-engine={{ docker_version }}"
  apt: "name=docker-engine={{ docker_version }} state=present"

- service: name=docker enabled=yes

- service: name=docker state=stopped
  register: docker_started
